### ISSUE TITLE
Invalid operands for multiplication

### ISSUE THREAD

**Issue by naimkhalifa** [callmenick/CSS-Circle-Menu#2]
Hi,

I'm trying to compile your Sass file with gulp in a Laravel project. 
I get the following error message when trying to compile:

`Sass Compilation Failed: bower_components/css-circle-menu/sass/circle-menu.scss Error: invalid operands for multiplication  on line 93 of bower_components/css-circle-menu/sass/circle-menu.scss >> $spread-radius: 144px !default;`  
`// [3]    ----------------^` 

note: this "------------^" points **1**44"

I have to admit I am used to less but new to Sass. 

Does anyone have an idea on how i could solve this?

Thx

**Comment by peterzen** [comment]
Hello,

did you find a solution eventually?  I bumped into the same issue.

The offending line is:
`translate(floor(-$r * cos($theta)), floor(-$r * sin($theta)))`

node-sass 3.4.2
sass-loader ^3.2.0

Many thanks!

**Comment by eldyvoon** [comment]
please fix this. Sigh.

**Comment by callmenick** [comment]
Did any of you go through the Readme? It says, very close to the top:

> The component makes heavy use of Sass, and also some Compass math helper functions. Sass is compiled via Gulp, and using Sass makes the component easily configurable. The menu items fly out along a quarter-circle with a given spread radius, so basic trigonometry and polar-to-cartesian math make calculating positions much easier, hence the use of Compass helpers.

In any case, I will update the component to not be dependent on ruby sass / compass, as it's outdated and I myself have moved away from it.
